name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/express-app
          git pull origin main
          docker stop express-app || true
          docker rm express-app || true
          docker rmi dadia/app:latest || true
          docker pull dadia/app:latest
          docker run -d --name express-app -p 80:5000 dadia/app:latest
